### ISSUE TITLE
Setting PS in .octaverc causes octave_kernel not to load

### ISSUE THREAD

**Issue by arogbonlo** [Calysto/octave_kernel#107]
I found that the following lines in  .octaverc causes octave_kernel to timeout without loading in jupyter notebook (as well as the qt and console). 

```
PS1('[\W]>> ')
PS2('')
```
Perhaps it has something to do with the prompt in the notebook.

**Comment by dsblank** [comment]
I think we have the whole system geared to know when it is ready for input based on the prompt. You can see that code here:

https://github.com/Calysto/octave_kernel/blob/master/octave_kernel/kernel.py#L22-L23

But you really shouldn't see those prompts, right? I guess what you are saying is that we should set the prompts ourselves so that if you have code like that, it will still work?

**Comment by blink1073** [comment]
We can re-override them after evaluating the octaverc file at startup.

**Comment by blink1073** [comment]
Should be fixed by: `pip install octave_kernel=0.28.2`
