### ISSUE TITLE
qt toolkit can't be enabled

### ISSUE THREAD

**Issue by viraghj** [Calysto/octave_kernel#164]
$ python -m octave_kernel.check
Octave kernel v0.31.0
Metakernel v0.24.3
Python v3.7.5 (default, Dec 15 2019, 17:54:26) 
[GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]
Python path: /usr/bin/python

Connecting to Octave...
Octave connection established
Octave Kernel v0.31.0 running GNU Octave v5.1.0
Graphics toolkit: fltk
Available toolkits: 
  [1,1] = fltk
  [1,2] = gnuplot
}

$ octave -q
octave:1> available_graphics_toolkits 
ans =
{
  [1,1] = fltk
  [1,2] = gnuplot
  [1,3] = qt
}

Fedora 31 with all the relevant packages installed/upgraded as RPM packages (no pip/conda/etc hacks)

**Comment by blink1073** [comment]
Hi @viraghj, are you launching the `octave-cli` executable when you see the `qt` toolkit?  We need to use `octave-cli` to prevent the Octave window from opening.

**Comment by viraghj** [comment]
No - it was the "true" octave binary. And now I realized, that octave-cli doesn't offer the qt toolkit.
So this is a dead end, really? My main concern is the use of Octave uicontrols in notebooks and it requires the qt toolkit.
After linking octave-cli to octave-5.2.1 qt can be enabled and the controls are created in their own windows, but without any interaction/callback activity. 

Then this example in  README.rst is misleading?
...
cat ~/.jupyter/octave_kernel_config.py
    # use Qt as the default backend for plots
    c.OctaveKernel.plot_settings = dict(backend='qt')
...

**Comment by pantxo** [comment]
>  We need to use octave-cli to prevent the Octave window from opening.
Recent versions of the octave binary (>= 4.4) don't launch the GUI by default, while older ones just need be launched using the "--no-gui" switch in order to avoid poping up a GUI window. The switch still exists in new versions of octave but has no effect. 

Using this switch would allow using the Qt toolkit which, contrary to the Gnuplot toolkit, is actively developed. It won't allow using "ui*" (including uicontrol) since "print" doesn't handle those.
