### ISSUE TITLE
Plotting doesn't work in Jupyter!(Arch Linux System) Installed, gnuplot

### ISSUE THREAD

**Issue by samipism** [Calysto/octave_kernel#195]
Hello, I am trying to plot a graph in jupyter notebook. I searched through various forums, where many of them suggested to install gnuplot, include graphics_toolkit("gnuplot"). 

I tried those, but none of the techniques worked. I guess, from the error, it is searching for the files related to fltk. Although, the graphics toolkit has been changed to gnuplot. Please help. Thank you in advance.
![image](https://user-images.githubusercontent.com/34964733/122030294-5f9d0000-cded-11eb-90e0-432666089490.png)

**Comment by YousefSaber** [comment]
facing the same issue, I made a previous [issue](https://github.com/Calysto/octave_kernel/issues/191) and got no response till now

**Comment by taffarel55** [comment]
I have the same issue on Manjaro

**Comment by SSimco** [comment]
I was able to plot a graph in jupyter notebook using qt. I had to make jupyter use the octave executable instead of octave-cli. To do that I had to make a symbolic link to it `ln -s /usr/bin/octave /usr/bin/octave-cli-jupyter` then set the environment variable `` export OCTAVE_EXECUTABLE=octave-cli-jupyter``, and then run ``jupyter notebook``. Now you can plot using qt.
![qtplot](https://user-images.githubusercontent.com/37044560/144467838-aeaa276d-10e4-4fa5-b2e2-507a104b406d.png)

**Comment by taffarel55** [comment]
Can you tell more details about what you did?

**Comment by SSimco** [comment]
> Can you tell more details about what you did?

When I run `octave-cli` in a terminal and run the command `available_graphics_toolkits()` I can only see that it has fltk and when I run `octave` in a terminal and run the same command I can see now that it also lists qt. So instead of figuring out how to make qt available for octave-cli I just use the octave executable. I also create a symbolic link to octave because octave_kernel checks if the octave command that it is using contains "octave-cli" in it's name. Then you just tell it to use that symbolic link instead of octave-cli and you can run it in a terminal with the command `env OCTAVE_EXECUTABLE=octave-cli-jupyter jupyter notebook` after you made octave-cli-jupyter.

**Comment by Plinsboorg** [comment]
![изображение](https://user-images.githubusercontent.com/42300339/145773940-7f09ea3e-5ca3-45d0-8eb9-ef95d5b2d079.png)
Adding the following phrase seems to help
set(gcf,'Visible','on');

But I have no idea what this line does.
