### ISSUE TITLE
figure size

### ISSUE THREAD

**Issue by oroszl** [Calysto/octave_kernel#4]
I just came across octave_kernel for ipython/jupyter and have played with it for a bit. (It seems to be just the sort of thing I desperately need for teaching) 
I had some issues regarding the plots, it seems that my figures are always way too big for my browser. I have tried to set the image size via the %plot magic but it had no effect.
Is there a generic/nice/default way of defining the image sizes ?
I am not even sure if this is a real "issue", I would be perfectly happy if someone would point me in the right direction.

**Comment by blink1073** [comment]
Hi @oroszl, %plot support (and a better default) will coming in the next release (hopefully this weekend).

**Comment by oroszl** [comment]
thanks for the quick answer!
I will keep checking out the updates!

**Comment by blink1073** [comment]
New release out!  Does it work for you?

**Comment by oroszl** [comment]
Hi,
seems that the default figure size is smaller, and now it fits snugly in the notebook.
however %plot has still no effect on the stuff..

**Comment by oroszl** [comment]
Hi again
so after some digging `%plot` works and setting the plot size also works BUT not the way it is written in the help..
I tried

    %plot -s 10,10

which produced some errors like: 'tuple' object has no attribute 'split' 
However after putting in some extra quotes like

    %plot inline -s '100,200' -f 'png'

I get the right behavior.. I am not sure if this is the standard and the help needs to be updated, or I did something to evoke this behavior. I run ipython from within a ipython/scipystack docker container
and install only octave and terminado to the container before cloning octave_kernel and installing it.
Anyway it seems now it works and thanks for your quick response and for the new version! Keep up the good work! 
Cheers!

**Comment by blink1073** [comment]
Should be fixed in 0.9.1, thanks for the feedback!

**Comment by akiross** [comment]
Sorry if I add myself to this issue, but I think it is related.

I am using 0.12.12 - from pip - and I have an issue when the plot is resized: the plot is completely black. I can see the axis, but plot's inside is jet-black.

I tried resizing using both:

    %plot -s 10,10

and 

    %plot inline -s '100,200' -f 'png'

but with the same result.

**Comment by akiross** [comment]
...But I just looked at the code and saw that you use the SVG format instead of PNG, and using that fixed the problem of the black image.

**Comment by blink1073** [comment]
So, is it working for you now @akiross?

**Comment by akiross** [comment]
Not entirely... Each solution is buggy.

png generation has the correct size on screen (e.g. 100x100 image is shown
on 100x100 pixels), but the plot area is black filled. Note, scales/numbers
on axis are visible and it is not the entire image to be black filled, just
the plotting area.

Svg renders correctly, but size does not reflect on screen: a 100x100 svg
will occupy the same area of a 500x500 svg, that is, both are scaled to fit
100% width of the containing HTML element. The final size ultimately
depends on the browser window size.

This may be or may be not considered a bug, but at least would be nice to
have some flags to control svg size in the HTML, instead of defaulting to
100%.

Is that possible?
(sorry for any typos but I wrote from the phone)

**Comment by blink1073** [comment]
@akiross, fixed and released.

**Comment by akiross** [comment]
Nice, thanks! :)
